server:
  port: 8088
spring:
  application:
    name: txwl
  data:
    mongodb:
      uri: mongodb://localhost:27017/face_platform  #mongodb://admin:admin@10.40.51.33:27018/face_platform
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce.pool.max-active: 8
    lettuce.pool.max-wait: -1
    lettuce.pool.max-idle: 8
    lettuce.pool.min-idle: 0

OpodDecOrEnc:
  url: http://10.40.51.33:9700

logging:
  config: classpath:log/logback-spring.xml